apiVersion: aws.platform.io/v1alpha1
kind: EKSCluster
metadata:
  name: dev-eks-cluster
  namespace: default
spec:
  parameters:
    clusterName: "dev-eks-cluster"
    region: "us-west-2"
    version: "1.31"
    nodeGroupConfig:
      instanceTypes: ["t3.medium", "t3.large"]
      minSize: 2
      maxSize: 10
      desiredSize: 3
      diskSize: 50
      capacityType: "ON_DEMAND"
    networking:
      vpcCidr: "10.0.0.0/16"
      enablePrivateEndpoint: true
      enablePublicEndpoint: false  # Private cluster - no public endpoint
      subnetCidrs:
        publicSubnets: ["10.0.1.0/24", "10.0.2.0/24"]  # Still needed for NAT Gateway
        privateSubnets: ["10.0.10.0/24", "10.0.20.0/24"]  # EKS cluster will use only these
    bastionConfig:
      enabled: true
      instanceType: "t3.micro"
      allowedCidrs: ["0.0.0.0/0"]  # Restrict this to your IP range for better security
      # publicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAA..."  # Add your SSH public key here
    tags:
      Environment: "development"
      Team: "platform-engineering"
      Project: "microservices"
      Owner: "devops-team"
      ManagedBy: "crossplane"
